# Generated by Django 4.0.4 on 2022-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='due_amount',
            field=models.IntegerField(default=0),
        ),
    ]
